version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/s2g
      - SECRET_KEY=your_secret_key_here
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8080"]
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_REDIRECT_URI=http://localhost:8000/api/v1/oauth/google/callback
    depends_on:
      - db
    volumes:
      - ./:/app
    restart: always
    # Add entrypoint to ensure start.sh has execute permissions
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/start.sh && /app/start.sh"]

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=s2g
    ports:
      - "5433:5432"

volumes:
  postgres_data: